In [52]:
import pandas as pd

In [53]:
loan = pd.read_csv('loan.csv', sep=',')
loan

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [54]:
loan.columns

Index(['Loan_ID', 'Gender', 'Married', 'Dependents', 'Education',
       'Self_Employed', 'ApplicantIncome', 'CoapplicantIncome', 'LoanAmount',
       'Loan_Amount_Term', 'Credit_History', 'Property_Area', 'Loan_Status'],
      dtype='object')

In [55]:
loan['Dependents'] = loan['Dependents'].replace('3+', '4')

In [56]:
loan['Dependents'] = pd.to_numeric(loan['Dependents'], errors='coerce')

In [57]:
loan['Loan_Status'].dtype

dtype('O')

In [58]:
loan['Loan_Status'] = (
    loan['Loan_Status']
    .astype(str)
    .str.strip()
    .str.lower()
    .map({'y':1, 'yes':1, 'n':0, 'no':0})
)

In [59]:
loan['LoanAmount'] = loan['LoanAmount'].fillna(0)

In [60]:
loan

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0.0,Graduate,No,5849,0.0,0.0,360.0,1.0,Urban,1
1,LP001003,Male,Yes,1.0,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,0
2,LP001005,Male,Yes,0.0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,1
3,LP001006,Male,Yes,0.0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,1
4,LP001008,Male,No,0.0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0.0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,1
610,LP002979,Male,Yes,4.0,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,1
611,LP002983,Male,Yes,1.0,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,1
612,LP002984,Male,Yes,2.0,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,1
613,LP002990,Female,No,0.0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,0

In [61]:
loan['Gender'].hasnans

True

In [62]:
loan['Gender'] = loan['Gender'].fillna('Female')

In [63]:
loan['Married'] = loan['Married'].fillna('No')

In [64]:
loan['Dependents'] = loan['Dependents'].fillna(0)

In [65]:
loan['Loan_Amount_Term'] = loan['Loan_Amount_Term'].fillna(0)

In [66]:
loan['Credit_History'] = loan['Credit_History'].fillna(1.0)

In [71]:
loan['Self_Employed'] = loan['Self_Employed'].replace(' ', 'No')

In [73]:
loan['Education'] = loan['Education'].replace(' ', 'not Graduate')

In [74]:
loan['ApplicantIncome'] = loan['ApplicantIncome'].fillna(0)

In [75]:
loan['CoapplicantIncome'] = loan['CoapplicantIncome'].fillna(0)

In [77]:
loan['LoanAmount'] = loan['LoanAmount'].fillna(0)

In [78]:
loan['Property_Area'] = loan['Property_Area'].fillna('Rural')

In [79]:
loan['Gender'].hasnans

False

In [80]:
loan.to_csv('loan_def.csv')